export enum TwitterErrorResponseCodes {
    "Bad Request" = 400,
    "Unauthorized" = 401,
    "Forbidden" = 403,
    "Not Found" = 404,
    "Not Acceptable" = 406,
    "Gone" = 410,
    "Enhance Your Calm" = 420,
    "Unprocessable Entity" = 422,
    "Too Many Requests" = 429,
    "Internal Server Error" = 500,
    "Bad Gateway" = 502,
    "Service Unavailable" = 503,
    "Gateway timeout" = 504,
}
